### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [Ternair-Software/tcl-template#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) The following URLs used in your template have been identified as malicious. Refer to the steps in this [help center article](https://support.google.com/adspolicy/answer/6020954#311) to fix the issue or remove these URLs from your template https://tcl.ternairsoftware.com

**Comment by ternairsoftware** [comment]
Hello @praveena-pappu 

Thank you for reviewing our template. 

We have updated the template:
- We have removed the marked URL from the template.
- We have updated the homepage & documentation URL's in the metadaya.yaml
- We have added a README.md with details about the tag, how to add the tag and how to configure it.
- We have expanded the template with a few fields to configure and some functionality

Would you be willing to take another look again to see if all of your issues have been resolved?

Thanks,

Taco Perquin
Ternair

**Comment by ternairsoftware** [comment]
Hi @praveena-pappu 

Just checking in, have you been able to take a look at our submission again?

Thanks,

Taco Perquin
Ternair
